name: vertexbarcode
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  mobile_scanner: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  
  barcode_widget: ^2.0.4
  screenshot: ^3.0.0 
  path_provider: ^2.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 2

  assets:
    - assets/icon.png